CREATE DATABASE DB_LOJAGENERATION;    
USE DB_LOJAGENERATION;

CREATE TABLE TB_CATEGORIA(
    ID BIGINT(5) AUTO_INCREMENT,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTOS(
    ID BIGINT(5) AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    PRECO DECIMAL(6,2) NOT NULL,
    QTDPRODUTO INT NOT NULL,
    CATEGORIA_ID BIGINT,
    PRIMARY KEY(ID),
    FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID)
) ;

INSERT INTO TB_CATEGORIA(DESCRICAO)
    VALUES("PERIFERICOS");
    
INSERT INTO TB_CATEGORIA(DESCRICAO)
    VALUES("SOFTWARE");
    
INSERT INTO TB_CATEGORIA(DESCRICAO)
    VALUES("ADESIVOS");    

SELECT * FROM TB_CATEGORIA;

INSERT INTO TB_PRODUTOS(NOME,PRECO,QTDPRODUTO,CATEGORIA_ID)
    VALUES("MOUSE",70.99,4,1);
   
INSERT INTO TB_PRODUTOS(NOME,PRECO,QTDPRODUTO,CATEGORIA_ID)
    VALUES("TECLADO",85.00,10,1);

INSERT INTO TB_PRODUTOS(NOME,PRECO,QTDPRODUTO,CATEGORIA_ID)
    VALUES("ONE PIECE",35.50,10,3);
    
SELECT * FROM TB_PRODUTOS;



SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA ON
TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIA.ID;

