CREATE DATABASE BD_RH;
USE BD_RH;
CREATE TABLE RH_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME CHAR(255),
SETOR CHAR(255),
FUNCAO CHAR(255),
IDADE INT,
SALARIO INT,
AFASTADO CHAR(255),
PRIMARY KEY(ID)
);

INSERT INTO RH_FUNCIONARIOS (NOME,SETOR,FUNCAO,IDADE,SALARIO, AFASTADO) 
VALUE ("RORONOA ZORO","DEFESA","ESPADACHIM",20,2000,"NÃO");
INSERT INTO RH_FUNCIONARIOS (NOME,SETOR,FUNCAO,IDADE,SALARIO, AFASTADO) 
VALUE ("CHOPPER","MEDICINA DO TRABALHO","MÉDICO",15,34000,"SIM");
INSERT INTO RH_FUNCIONARIOS (NOME,SETOR,FUNCAO,IDADE,SALARIO,AFASTADO) 
VALUE ("IONA","NAVEGAÇÃO","NAVIO DE COMBATE",18,44532,"NÃO");
INSERT INTO RH_FUNCIONARIOS (NOME,SETOR,FUNCAO,IDADE,SALARIO, AFASTADO) 
VALUE ("NAMI","NAVEGAÇÃO","NAVEGADORA",23,50000,"NÃO");
INSERT INTO RH_FUNCIONARIOS (NOME,SETOR,FUNCAO,IDADE,SALARIO, AFASTADO) 
VALUE ("MONKEY D. LUFFY","ADMINISTRATIVO","CAPITÃO",17,1000000,"NÃO");
INSERT INTO RH_FUNCIONARIOS (NOME,SETOR,FUNCAO,IDADE,SALARIO, AFASTADO) 
VALUE ("SANJI","ALIMENTAÇÃO","COZINHEIRO",28,5000,"NÃO");
INSERT INTO RH_FUNCIONARIOS (NOME,SETOR,FUNCAO,IDADE,SALARIO, AFASTADO) 
VALUE ("SANJI","ALIMENTAÇÃO","COZINHEIRO",28,5000,"NÃO");

SELECT * FROM RH_FUNCIONARIOS WHERE SALARIO > 20000;
SELECT * FROM RH_FUNCIONARIOS WHERE SALARIO < 20000;

SELECT * FROM RH_FUNCIONARIOS ;

UPDATE RH_FUNCIONARIOS SET SALARIO = 25000 WHERE ID = 1;

DELETE FROM RH_FUNCIONARIOS WHERE ID BETWEEN 7 AND 13;

